# Generated by Django 5.0.6 on 2024-07-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('authors', models.JSONField(default=list)),
                ('publisher', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('description', models.TextField()),
                ('categories', models.JSONField(default=list)),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
