# Generated by Django 5.0.6 on 2024-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(max_length=1024),
        ),
    ]
