# Generated by Django 5.0.6 on 2024-07-09 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookdislikes_booklikes_bookrating_bookreads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReads',
            new_name='BookDislike',
        ),
        migrations.RenameModel(
            old_name='BookLikes',
            new_name='BookLike',
        ),
        migrations.RenameModel(
            old_name='BookDislikes',
            new_name='BookRead',
        ),
    ]
